/**
 * Blog Page - High Desert Modernism Design
 * SEO-optimized blog posts from database (auto-generated by LLM)
 * Links back to reacohomes.com for authority building
 */

import { useState } from "react";
import Header from "@/components/Header";
import Breadcrumb, { breadcrumbConfigs } from "@/components/Breadcrumb";
import PageSEO from "@/components/PageSEO";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import {
  ArrowRight,
  Calendar,
  User,
  Clock,
  Tag,
  ExternalLink,
  ChevronRight,
  Eye,
  Loader2,
} from "lucide-react";
import { calculateReadingTime, formatReadingTime } from "@/components/ReadingTime";

const popularTags = [
  "Brasada Ranch",
  "Tetherow",
  "Pronghorn",
  "Custom Homes",
  "Central Oregon",
  "Bend Oregon",
  "Luxury Homes",
  "High Desert",
  "Building Process",
  "Home Design",
];

export default function Blog() {
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  
  // Fetch articles from database
  const { data: articles, isLoading } = trpc.articles.list.useQuery({});

  // Sort articles by publishedAt descending (newest first) and filter by category if selected
  const sortedArticles = articles
    ?.slice()
    .sort((a, b) => {
      const dateA = a.publishedAt ? new Date(a.publishedAt).getTime() : 0;
      const dateB = b.publishedAt ? new Date(b.publishedAt).getTime() : 0;
      return dateB - dateA; // Newest first
    });
  
  const filteredArticles = selectedCategory
    ? sortedArticles?.filter((article) => article.category === selectedCategory)
    : sortedArticles;

  // Get featured articles (first 2 with most views)
  const featuredArticles = articles
    ?.slice()
    .sort((a, b) => (b.views || 0) - (a.views || 0))
    .slice(0, 2);

  // Get unique categories from articles
  const categories = articles
    ? Array.from(new Set(articles.map((a) => a.category).filter(Boolean)))
    : [];

  return (
    <div className="min-h-screen">
      <PageSEO
        title="Rea Co Homes Blog - Custom Home Building Insights"
        description="Expert insights on custom home building in Central Oregon. Tips, trends, and community guides from master builder Kevin Rea."
        keywords={["custom home building blog", "Central Oregon home tips", "luxury home design ideas", "Bend Oregon builder insights", "home construction guide"]}
        ogImage="https://d2xsxph8kpxj0f.cloudfront.net/310519663234433834/jH6DLQ8FrZGu3jgVut4Sqk/hero-main_2cc4c17d.jpg"
      />
      <Header />

      {/* Hero Section */}
      <section className="relative h-[50vh] flex items-center">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: "url('https://d2xsxph8kpxj0f.cloudfront.net/310519663234433834/jH6DLQ8FrZGu3jgVut4Sqk/hero-portfolio_1a2f7d27.jpg')" }}
        >
          <div className="absolute inset-0 bg-timber/80" />
        </div>

        <div className="container relative z-10 text-center">
          <Breadcrumb items={breadcrumbConfigs.blog} className="justify-center mb-6 text-white/70 [&_a]:text-white/70 [&_a:hover]:text-amber [&_span]:text-white" />
          <p className="font-body text-amber uppercase tracking-widest text-sm mb-4 animate-fade-in">
            Insights & Expertise
          </p>
          <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-semibold text-white mb-6 animate-fade-in-up">
            Rea Co Homes Blog
          </h1>
          <p className="font-body text-xl text-white/90 max-w-2xl mx-auto animate-fade-in-up animation-delay-200">
            Expert insights on custom home building, Central Oregon communities, and luxury living from Kevin Rea.
          </p>
        </div>
      </section>

      {/* Blog Content */}
      <section className="py-16 bg-cream">
        <div className="container">
          <div className="grid lg:grid-cols-3 gap-12">
            {/* Main Content */}
            <div className="lg:col-span-2">
              {/* Loading State */}
              {isLoading ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="w-8 h-8 animate-spin text-amber" />
                  <span className="ml-3 text-muted-foreground">Loading articles...</span>
                </div>
              ) : (
                <>
                  {/* Featured Posts */}
                  {!selectedCategory && featuredArticles && featuredArticles.length > 0 && (
                    <div className="mb-12">
                      <h2 className="font-display text-2xl font-semibold text-timber mb-6">
                        Featured Articles
                      </h2>
                      <div className="grid md:grid-cols-2 gap-6">
                        {featuredArticles.map((article) => (
                          <Link key={article.id} href={`/articles/${article.slug}`}>
                            <Card className="group overflow-hidden border-0 shadow-lg hover:shadow-xl transition-all duration-500 cursor-pointer h-full">
                              <div className="relative h-48 overflow-hidden bg-stone">
                                {article.featuredImage ? (
                                  <img
                                    src={article.featuredImage}
                                    alt={`${article.title} - ${article.category || 'Custom Home'} in Central Oregon by Kevin Rea, Bend Oregon luxury home builder`}
                                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                                  />
                                ) : (
                                  <div className="absolute inset-0 bg-gradient-to-br from-timber/20 to-amber/20" />
                                )}
                                <div className="absolute top-4 left-4">
                                  <span className="font-body text-xs bg-amber text-timber px-3 py-1 rounded-full font-medium">
                                    Featured
                                  </span>
                                </div>
                              </div>
                              <CardContent className="p-6">
                                <h3 className="font-display text-lg font-semibold text-timber mb-2 line-clamp-2 group-hover:text-amber transition-colors">
                                  {article.title}
                                </h3>
                                <p className="font-body text-muted-foreground text-sm mb-4 line-clamp-2">
                                  {article.excerpt}
                                </p>
                                <div className="flex items-center gap-4 text-xs text-muted-foreground">
                                  <span className="flex items-center gap-1">
                                    <Calendar className="w-3 h-3" />
                                    {article.publishedAt
                                      ? new Date(article.publishedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'numeric', day: 'numeric' })
                                      : "Draft"}
                                  </span>
                                  <span className="flex items-center gap-1">
                                    <Eye className="w-3 h-3" />
                                    {article.views} views
                                  </span>
                                </div>
                              </CardContent>
                            </Card>
                          </Link>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* All Posts */}
                  <div>
                    <div className="flex items-center justify-between mb-6">
                      <h2 className="font-display text-2xl font-semibold text-timber">
                        {selectedCategory ? `Articles in "${selectedCategory}"` : "All Articles"}
                      </h2>
                      {selectedCategory && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setSelectedCategory(null)}
                          className="border-timber text-timber"
                        >
                          Clear Filter
                        </Button>
                      )}
                    </div>

                    {filteredArticles && filteredArticles.length > 0 ? (
                      <div className="space-y-8">
                        {filteredArticles.map((article, index) => (
                          <Link key={article.id} href={`/articles/${article.slug}`}>
                            <Card
                              className="group overflow-hidden border-0 shadow-lg hover:shadow-xl transition-all duration-500 animate-fade-in-up cursor-pointer"
                              style={{ animationDelay: `${index * 100}ms` }}
                            >
                              <div className="flex flex-col md:flex-row">
                                <div className="md:w-1/3 h-48 md:h-auto overflow-hidden bg-stone">
                                  {article.featuredImage ? (
                                    <img
                                      src={article.featuredImage}
                                      alt={`${article.title} - ${article.category || 'Custom Home Building'} article by Kevin Rea, Central Oregon luxury home builder serving Brasada Ranch, Tetherow, Pronghorn`}
                                      className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                                    />
                                  ) : (
                                    <div className="w-full h-full bg-gradient-to-br from-timber/20 to-amber/20 flex items-center justify-center">
                                      <span className="text-timber/50 font-display text-sm">{article.category}</span>
                                    </div>
                                  )}
                                </div>
                                <CardContent className="md:w-2/3 p-6">
                                  <div className="flex items-center gap-4 mb-3 text-sm text-muted-foreground">
                                    <span className="flex items-center gap-1">
                                      <User className="w-3 h-3" />
                                      Kevin Rea
                                    </span>
                                    <span className="flex items-center gap-1">
                                      <Calendar className="w-3 h-3" />
                                      {article.publishedAt
                                        ? new Date(article.publishedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'numeric', day: 'numeric' })
                                        : "Draft"}
                                    </span>
                                    <span className="flex items-center gap-1">
                                      <Eye className="w-3 h-3" />
                                      {article.views} views
                                    </span>
                                    <span className="flex items-center gap-1">
                                      <Clock className="w-3 h-3" />
                                      {formatReadingTime(calculateReadingTime(article.content || article.excerpt || ''))}
                                    </span>
                                  </div>
                                  <h3 className="font-display text-xl font-semibold text-timber mb-3 group-hover:text-amber transition-colors">
                                    {article.title}
                                  </h3>
                                  <p className="font-body text-muted-foreground mb-4 line-clamp-2">
                                    {article.excerpt}
                                  </p>
                                  <div className="flex flex-wrap gap-2 mb-4">
                                    {article.category && (
                                      <span className="font-body text-xs bg-amber/20 text-amber px-2 py-1 rounded flex items-center gap-1">
                                        <Tag className="w-3 h-3" />
                                        {article.category}
                                      </span>
                                    )}
                                    {article.tags?.split(",").slice(0, 2).map((tag) => (
                                      <span
                                        key={tag}
                                        className="font-body text-xs bg-stone px-2 py-1 rounded text-timber"
                                      >
                                        {tag.trim()}
                                      </span>
                                    ))}
                                  </div>
                                  <span className="font-body text-sm text-amber font-medium flex items-center gap-1 group-hover:gap-2 transition-all">
                                    Read Full Article
                                    <ChevronRight className="w-4 h-4" />
                                  </span>
                                </CardContent>
                              </div>
                            </Card>
                          </Link>
                        ))}
                      </div>
                    ) : (
                      <Card className="border-0 shadow-lg">
                        <CardContent className="p-12 text-center">
                          <Tag className="w-12 h-12 text-amber mx-auto mb-4" />
                          <h3 className="font-display text-xl font-semibold text-timber mb-2">
                            No Articles Yet
                          </h3>
                          <p className="text-muted-foreground">
                            Check back soon for new content!
                          </p>
                        </CardContent>
                      </Card>
                    )}
                  </div>
                </>
              )}
            </div>

            {/* Sidebar */}
            <div className="lg:col-span-1">
              {/* About Author */}
              <Card className="border-0 shadow-lg mb-8">
                <CardContent className="p-6">
                  <h3 className="font-display text-lg font-semibold text-timber mb-4">
                    About the Author
                  </h3>
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-16 h-16 rounded-full bg-stone overflow-hidden">
                      <img
                        src="https://d2xsxph8kpxj0f.cloudfront.net/310519663234433834/jH6DLQ8FrZGu3jgVut4Sqk/kevin-rea_d8906d02.webp"
                        alt="Kevin Rea"
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div>
                      <p className="font-display font-semibold text-timber">
                        Kevin Rea
                      </p>
                      <p className="font-body text-sm text-muted-foreground">
                        Master Builder
                      </p>
                    </div>
                  </div>
                  <p className="font-body text-sm text-muted-foreground mb-4">
                    With over 45 years of experience building luxury custom homes
                    in Central Oregon, Kevin shares his expertise and insights on
                    the art of home building.
                  </p>
                  <a
                    href="https://www.reacohomes.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="font-body text-sm text-amber flex items-center gap-1 hover:gap-2 transition-all"
                  >
                    Visit Official Website
                    <ExternalLink className="w-4 h-4" />
                  </a>
                </CardContent>
              </Card>

              {/* Categories */}
              <Card className="border-0 shadow-lg mb-8">
                <CardContent className="p-6">
                  <h3 className="font-display text-lg font-semibold text-timber mb-4">
                    Categories
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {categories.map((category) => (
                      <button
                        key={category}
                        onClick={() => setSelectedCategory(category === selectedCategory ? null : category)}
                        className={`font-body text-sm px-3 py-1 rounded-full transition-colors ${
                          selectedCategory === category
                            ? "bg-amber text-timber"
                            : "bg-stone text-timber hover:bg-amber/20"
                        }`}
                      >
                        {category}
                      </button>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Popular Tags */}
              <Card className="border-0 shadow-lg mb-8">
                <CardContent className="p-6">
                  <h3 className="font-display text-lg font-semibold text-timber mb-4">
                    Popular Topics
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {popularTags.map((tag) => (
                      <span
                        key={tag}
                        className="font-body text-sm px-3 py-1 rounded-full bg-stone text-timber"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* CTA */}
              <Card className="border-0 shadow-lg bg-timber text-white">
                <CardContent className="p-6">
                  <h3 className="font-display text-lg font-semibold mb-4">
                    Ready to Build?
                  </h3>
                  <p className="font-body text-sm text-white/80 mb-6">
                    Contact Kevin Rea for a free consultation about your custom
                    home project.
                  </p>
                  <Link href="/contact">
                    <Button className="w-full bg-amber text-timber hover:bg-amber/90 font-body font-semibold">
                      Get Started
                      <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                  </Link>
                  <p className="font-body text-sm text-white/60 mt-4 text-center">
                    Call: 541-390-9848
                  </p>
                </CardContent>
              </Card>

              {/* Related Searches for SEO */}
              <div className="mt-8">
                <h4 className="font-body text-sm text-muted-foreground mb-3">
                  Related Searches
                </h4>
                <div className="space-y-2 text-sm text-muted-foreground">
                  <p>custom home builder Bend Oregon</p>
                  <p>luxury homes Brasada Ranch</p>
                  <p>Tetherow custom home builder</p>
                  <p>Central Oregon home construction</p>
                  <p>high desert custom homes</p>
                  <p>Pronghorn luxury builder</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
